name: update-bing-walpaper

on:
  push:
    branches:
     - master
  schedule:
   - cron: "30 0,18 * * *"

env:
  STORAGE_TYPE: mongodb
  # mongodb配置
  MONGODB_URI: ${{ secrets.MONGODB_URI }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@master
    
     - name: Set up Python
       uses: actions/setup-python@v1
       with:
        python-version: 3.8

     - name: Install Requirements
       working-directory: ./bing_api
       run: |
         pip install -r requirements.txt
 
     - name: mongodb Update bing
       if: ${{ env.STORAGE_TYPE == 'mongodb' }}  
       env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
       working-directory: ./
       run: |
         python bing_api/run.py
