name: update-bing-image-api

on:
  push:
    branches:
     - master
  schedule:
   - cron: "0 0,6,12,18,21 * * *"
  watch:
    types: [started]

env:
  # mongodb配置
  MONGODB_URI: ${{ secrets.MONGODB_URI }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id # 自己点的start
    steps:
     - name: Checkout
       uses: actions/checkout@master
    
     - name: Set up Python
       uses: actions/setup-python@v1
       with:
        python-version: 3.8

     - name: Install Requirements
       working-directory: ./bing-image-api
       run: |
         pip install -r requirements.txt
 
     - name: mongodb Update bing #mongodb
       env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
       working-directory: ./bing-image-api
       run: |
         python run.py